const studentsData = [
  {
    id: "STU001",
    rollNumber: "23CS101",
    name: "Aakash Sharma",
    email: "aakash.s@college.edu",
    phone: "+91 91234 56701",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Male",
    bloodGroup: "B+",
    attendancePercentage: 88,
    cgpa: 8.7,
    status: "Active",
    guardianName: "R. K. Sharma",
    guardianPhone: "+91 98111 22331",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU002",
    rollNumber: "23CS102",
    name: "Ananya Patel",
    email: "ananya.p@college.edu",
    phone: "+91 91234 56702",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Female",
    bloodGroup: "O+",
    attendancePercentage: 94,
    cgpa: 9.3,
    status: "Active",
    guardianName: "S. Patel",
    guardianPhone: "+91 98111 22332",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU003",
    rollNumber: "23CS103",
    name: "Deepak Verma",
    email: "deepak.v@college.edu",
    phone: "+91 91234 56703",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Male",
    bloodGroup: "A+",
    attendancePercentage: 72,
    cgpa: 7.4,
    status: "Active",
    guardianName: "M. Verma",
    guardianPhone: "+91 98111 22333",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU004",
    rollNumber: "23CS104",
    name: "Divya Nambiar",
    email: "divya.n@college.edu",
    phone: "+91 91234 56704",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Female",
    bloodGroup: "AB+",
    attendancePercentage: 91,
    cgpa: 8.9,
    status: "Active",
    guardianName: "K. Nambiar",
    guardianPhone: "+91 98111 22334",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU005",
    rollNumber: "23CS105",
    name: "Harish Iyer",
    email: "harish.i@college.edu",
    phone: "+91 91234 56705",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Male",
    bloodGroup: "O-",
    attendancePercentage: 81,
    cgpa: 8.0,
    status: "Active",
    guardianName: "G. Iyer",
    guardianPhone: "+91 98111 22335",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU006",
    rollNumber: "23CS106",
    name: "Ishita Roy",
    email: "ishita.r@college.edu",
    phone: "+91 91234 56706",
    department: "Computer Science & Engineering",
    className: "CSE-3A",
    semester: 5,
    gender: "Female",
    bloodGroup: "A-",
    attendancePercentage: 64,
    cgpa: 6.8,
    status: "Active",
    guardianName: "P. Roy",
    guardianPhone: "+91 98111 22336",
    enrolledSubjects: ["CS301", "CS302"]
  },
  {
    id: "STU007",
    rollNumber: "23CS201",
    name: "Karan Johar",
    email: "karan.j@college.edu",
    phone: "+91 91234 56707",
    department: "Computer Science & Engineering",
    className: "CSE-3B",
    semester: 5,
    gender: "Male",
    bloodGroup: "B+",
    attendancePercentage: 85,
    cgpa: 8.2,
    status: "Active",
    guardianName: "V. Johar",
    guardianPhone: "+91 98111 22337",
    enrolledSubjects: ["CS301"]
  },
  {
    id: "STU008",
    rollNumber: "23CS202",
    name: "Meera Reddy",
    email: "meera.r@college.edu",
    phone: "+91 91234 56708",
    department: "Computer Science & Engineering",
    className: "CSE-3B",
    semester: 5,
    gender: "Female",
    bloodGroup: "O+",
    attendancePercentage: 96,
    cgpa: 9.6,
    status: "Active",
    guardianName: "N. Reddy",
    guardianPhone: "+91 98111 22338",
    enrolledSubjects: ["CS301"]
  },
  {
    id: "STU009",
    rollNumber: "23CS203",
    name: "Naveen Rao",
    email: "naveen.r@college.edu",
    phone: "+91 91234 56709",
    department: "Computer Science & Engineering",
    className: "CSE-3B",
    semester: 5,
    gender: "Male",
    bloodGroup: "B-",
    attendancePercentage: 78,
    cgpa: 7.9,
    status: "Active",
    guardianName: "T. Rao",
    guardianPhone: "+91 98111 22339",
    enrolledSubjects: ["CS301"]
  },
  {
    id: "STU010",
    rollNumber: "23CS204",
    name: "Pooja Hegde",
    email: "pooja.h@college.edu",
    phone: "+91 91234 56710",
    department: "Computer Science & Engineering",
    className: "CSE-3B",
    semester: 5,
    gender: "Female",
    bloodGroup: "A+",
    attendancePercentage: 89,
    cgpa: 8.5,
    status: "Active",
    guardianName: "D. Hegde",
    guardianPhone: "+91 98111 22340",
    enrolledSubjects: ["CS301"]
  },
  {
    id: "STU011",
    rollNumber: "23IT301",
    name: "Rahul Deshmukh",
    email: "rahul.d@college.edu",
    phone: "+91 91234 56711",
    department: "Information Technology",
    className: "IT-3A",
    semester: 5,
    gender: "Male",
    bloodGroup: "O+",
    attendancePercentage: 92,
    cgpa: 8.6,
    status: "Active",
    guardianName: "S. Deshmukh",
    guardianPhone: "+91 98111 22341",
    enrolledSubjects: ["CS305"]
  },
  {
    id: "STU012",
    rollNumber: "23IT302",
    name: "Roshni Sen",
    email: "roshni.s@college.edu",
    phone: "+91 91234 56712",
    department: "Information Technology",
    className: "IT-3A",
    semester: 5,
    gender: "Female",
    bloodGroup: "AB-",
    attendancePercentage: 84,
    cgpa: 8.1,
    status: "Active",
    guardianName: "B. Sen",
    guardianPhone: "+91 98111 22342",
    enrolledSubjects: ["CS305"]
  },
  {
    id: "STU013",
    rollNumber: "23IT303",
    name: "Siddharth Malhotra",
    email: "siddharth.m@college.edu",
    phone: "+91 91234 56713",
    department: "Information Technology",
    className: "IT-3A",
    semester: 5,
    gender: "Male",
    bloodGroup: "B+",
    attendancePercentage: 68,
    cgpa: 7.2,
    status: "Active",
    guardianName: "A. Malhotra",
    guardianPhone: "+91 98111 22343",
    enrolledSubjects: ["CS305"]
  },
  {
    id: "STU014",
    rollNumber: "23IT304",
    name: "Tanvi Kulkarni",
    email: "tanvi.k@college.edu",
    phone: "+91 91234 56714",
    department: "Information Technology",
    className: "IT-3A",
    semester: 5,
    gender: "Female",
    bloodGroup: "A+",
    attendancePercentage: 95,
    cgpa: 9.1,
    status: "Active",
    guardianName: "Y. Kulkarni",
    guardianPhone: "+91 98111 22344",
    enrolledSubjects: ["CS305"]
  }
];

module.exports = { studentsData };
