import type {
  SubjectAttendance,
  AttendanceRecord,
  MonthlyAttendance,
  TimetableSlot,
  SemesterResult,
  ExamSchedule,
} from '../types/academic';

export const mockSubjectAttendance: SubjectAttendance[] = [
  {
    subjectId: 'sub-601',
    subjectCode: 'CS601',
    subjectName: 'Database Management Systems',
    staffName: 'Dr. Robert Chen',
    totalClasses: 42,
    present: 37,
    absent: 5,
    percentage: 88.1,
    status: 'Safe',
  },
  {
    subjectId: 'sub-602',
    subjectCode: 'CS602',
    subjectName: 'Design & Analysis of Algorithms',
    staffName: 'Prof. Sarah Jenkins',
    totalClasses: 40,
    present: 34,
    absent: 6,
    percentage: 85.0,
    status: 'Safe',
  },
  {
    subjectId: 'sub-603',
    subjectCode: 'CS603',
    subjectName: 'Web Fullstack Engineering',
    staffName: 'Dr. Alan Turing',
    totalClasses: 38,
    present: 35,
    absent: 3,
    percentage: 92.1,
    status: 'Safe',
  },
  {
    subjectId: 'sub-604',
    subjectCode: 'CS604',
    subjectName: 'Computer Networks & Security',
    staffName: 'Prof. David Vance',
    totalClasses: 44,
    present: 32,
    absent: 12,
    percentage: 72.7,
    status: 'Warning',
  },
  {
    subjectId: 'sub-605',
    subjectCode: 'CS605',
    subjectName: 'Cloud Infrastructure & DevOps',
    staffName: 'Dr. Emily Watson',
    totalClasses: 36,
    present: 31,
    absent: 5,
    percentage: 86.1,
    status: 'Safe',
  },
  {
    subjectId: 'sub-606',
    subjectCode: 'CS606',
    subjectName: 'Artificial Intelligence Fundamentals',
    staffName: 'Prof. James Smith',
    totalClasses: 30,
    present: 20,
    absent: 10,
    percentage: 66.7,
    status: 'Critical',
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: 'att-1', date: '2026-10-01', subjectCode: 'CS601', subjectName: 'Database Systems', status: 'Present', topicCovered: 'Indexing & B-Trees Optimization' },
  { id: 'att-2', date: '2026-10-01', subjectCode: 'CS603', subjectName: 'Web Engineering', status: 'Present', topicCovered: 'REST vs GraphQL API Architectures' },
  { id: 'att-3', date: '2026-09-30', subjectCode: 'CS602', subjectName: 'Algorithms', status: 'Present', topicCovered: 'Dynamic Programming - Knapsack Problem' },
  { id: 'att-4', date: '2026-09-30', subjectCode: 'CS604', subjectName: 'Computer Networks', status: 'Absent', topicCovered: 'TCP Congestion Avoidance Algorithms' },
  { id: 'att-5', date: '2026-09-29', subjectCode: 'CS605', subjectName: 'Cloud Infra', status: 'Present', topicCovered: 'Kubernetes Pod Lifecycle & Deployment' },
  { id: 'att-6', date: '2026-09-28', subjectCode: 'CS606', subjectName: 'Artificial Intelligence', status: 'Absent', topicCovered: 'Heuristic Search & A* Algorithm' },
];

export const mockMonthlyAttendance: MonthlyAttendance[] = [
  { month: 'Jun', percentage: 91.5, classesHeld: 36, classesAttended: 33 },
  { month: 'Jul', percentage: 86.4, classesHeld: 44, classesAttended: 38 },
  { month: 'Aug', percentage: 89.0, classesHeld: 40, classesAttended: 35 },
  { month: 'Sep', percentage: 81.2, classesHeld: 48, classesAttended: 39 },
  { month: 'Oct', percentage: 84.5, classesHeld: 24, classesAttended: 20 },
];

export const mockTimetableSlots: TimetableSlot[] = [
  { id: 'tt-1', day: 'Monday', startTime: '09:00 AM', endTime: '10:00 AM', subjectCode: 'CS601', subjectName: 'Database Management Systems', staffName: 'Dr. Robert Chen', venue: 'Hall 204', courseType: 'Theory' },
  { id: 'tt-2', day: 'Monday', startTime: '10:15 AM', endTime: '11:15 AM', subjectCode: 'CS602', subjectName: 'Design & Analysis of Algorithms', staffName: 'Prof. Sarah Jenkins', venue: 'Hall 204', courseType: 'Theory' },
  { id: 'tt-3', day: 'Monday', startTime: '11:30 AM', endTime: '01:30 PM', subjectCode: 'CS603L', subjectName: 'Web Engineering Laboratory', staffName: 'Dr. Alan Turing', venue: 'Lab 3 (Advanced Software)', courseType: 'Lab' },
  { id: 'tt-4', day: 'Tuesday', startTime: '09:00 AM', endTime: '10:00 AM', subjectCode: 'CS604', subjectName: 'Computer Networks & Security', staffName: 'Prof. David Vance', venue: 'Hall 105', courseType: 'Theory' },
  { id: 'tt-5', day: 'Tuesday', startTime: '10:15 AM', endTime: '11:15 AM', subjectCode: 'CS605', subjectName: 'Cloud Infrastructure & DevOps', staffName: 'Dr. Emily Watson', venue: 'Hall 105', courseType: 'Theory' },
  { id: 'tt-6', day: 'Wednesday', startTime: '09:00 AM', endTime: '11:00 AM', subjectCode: 'CS601L', subjectName: 'Database Systems Lab', staffName: 'Dr. Robert Chen', venue: 'Lab 1', courseType: 'Lab' },
  { id: 'tt-7', day: 'Wednesday', startTime: '11:30 AM', endTime: '12:30 PM', subjectCode: 'CS606', subjectName: 'Artificial Intelligence', staffName: 'Prof. James Smith', venue: 'Hall 204', courseType: 'Theory' },
  { id: 'tt-8', day: 'Thursday', startTime: '09:00 AM', endTime: '10:00 AM', subjectCode: 'CS602', subjectName: 'Algorithms', staffName: 'Prof. Sarah Jenkins', venue: 'Hall 204', courseType: 'Theory' },
  { id: 'tt-9', day: 'Thursday', startTime: '10:15 AM', endTime: '12:15 PM', subjectCode: 'CS605L', subjectName: 'Cloud Lab', staffName: 'Dr. Emily Watson', venue: 'Lab 4', courseType: 'Lab' },
  { id: 'tt-10', day: 'Friday', startTime: '09:00 AM', endTime: '10:00 AM', subjectCode: 'CS603', subjectName: 'Web Fullstack Engineering', staffName: 'Dr. Alan Turing', venue: 'Hall 204', courseType: 'Theory' },
  { id: 'tt-11', day: 'Friday', startTime: '10:15 AM', endTime: '11:15 AM', subjectCode: 'CS606', subjectName: 'Artificial Intelligence', staffName: 'Prof. James Smith', venue: 'Hall 204', courseType: 'Theory' },
];

export const mockSemesterResults: Record<number, SemesterResult> = {
  5: {
    semester: 5,
    sgpa: 8.92,
    cgpa: 8.78,
    totalCredits: 24,
    passedCredits: 24,
    resultStatus: 'PASSED',
    publishedDate: '2026-01-20',
    subjects: [
      { subjectCode: 'CS501', subjectName: 'Operating System Architecture', credits: 4, internalMarks: 38, externalMarks: 54, totalMarks: 92, grade: 'S', resultStatus: 'PASS' },
      { subjectCode: 'CS502', subjectName: 'Software Engineering & Agile', credits: 4, internalMarks: 35, externalMarks: 50, totalMarks: 85, grade: 'A+', resultStatus: 'PASS' },
      { subjectCode: 'CS503', subjectName: 'Theory of Computation & Automata', credits: 4, internalMarks: 34, externalMarks: 48, totalMarks: 82, grade: 'A+', resultStatus: 'PASS' },
      { subjectCode: 'CS504', subjectName: 'Microprocessors & Embedded Systems', credits: 4, internalMarks: 32, externalMarks: 44, totalMarks: 76, grade: 'A', resultStatus: 'PASS' },
      { subjectCode: 'CS505', subjectName: 'Compiler Design Principles', credits: 4, internalMarks: 36, externalMarks: 52, totalMarks: 88, grade: 'A+', resultStatus: 'PASS' },
      { subjectCode: 'CS506', subjectName: 'Professional Ethics & Management', credits: 4, internalMarks: 39, externalMarks: 56, totalMarks: 95, grade: 'S', resultStatus: 'PASS' },
    ],
  },
  4: {
    semester: 4,
    sgpa: 8.65,
    cgpa: 8.72,
    totalCredits: 22,
    passedCredits: 22,
    resultStatus: 'PASSED',
    publishedDate: '2025-07-15',
    subjects: [
      { subjectCode: 'CS401', subjectName: 'Computer Organization & Architecture', credits: 4, internalMarks: 36, externalMarks: 48, totalMarks: 84, grade: 'A+', resultStatus: 'PASS' },
      { subjectCode: 'CS402', subjectName: 'Object Oriented Programming in Java', credits: 4, internalMarks: 38, externalMarks: 55, totalMarks: 93, grade: 'S', resultStatus: 'PASS' },
      { subjectCode: 'CS403', subjectName: 'Discrete Mathematical Structures', credits: 4, internalMarks: 31, externalMarks: 43, totalMarks: 74, grade: 'A', resultStatus: 'PASS' },
      { subjectCode: 'CS404', subjectName: 'Data Communications', credits: 4, internalMarks: 33, externalMarks: 46, totalMarks: 79, grade: 'A', resultStatus: 'PASS' },
      { subjectCode: 'CS405', subjectName: 'Environmental Science', credits: 6, internalMarks: 37, externalMarks: 50, totalMarks: 87, grade: 'A+', resultStatus: 'PASS' },
    ],
  },
  3: {
    semester: 3,
    sgpa: 8.80,
    cgpa: 8.75,
    totalCredits: 22,
    passedCredits: 22,
    resultStatus: 'PASSED',
    publishedDate: '2025-01-18',
    subjects: [
      { subjectCode: 'CS301', subjectName: 'Data Structures & Algorithms', credits: 4, internalMarks: 39, externalMarks: 54, totalMarks: 93, grade: 'S', resultStatus: 'PASS' },
      { subjectCode: 'CS302', subjectName: 'Digital Logic & Circuit Design', credits: 4, internalMarks: 34, externalMarks: 48, totalMarks: 82, grade: 'A+', resultStatus: 'PASS' },
      { subjectCode: 'CS303', subjectName: 'Linear Algebra & Probability', credits: 4, internalMarks: 36, externalMarks: 50, totalMarks: 86, grade: 'A+', resultStatus: 'PASS' },
    ],
  },
};

export const mockExamSchedules: ExamSchedule[] = [
  {
    id: 'ex-1',
    date: '2026-10-15',
    day: 'Thursday',
    time: '10:00 AM - 01:00 PM',
    subjectCode: 'CS601',
    subjectName: 'Database Management Systems',
    examType: 'End-Semester Theory',
    venue: 'Main Exam Hall - Block A',
    seatNumber: 'A-42',
    durationMinutes: 180,
    totalMarks: 100,
  },
  {
    id: 'ex-2',
    date: '2026-10-18',
    day: 'Sunday',
    time: '10:00 AM - 01:00 PM',
    subjectCode: 'CS602',
    subjectName: 'Design & Analysis of Algorithms',
    examType: 'End-Semester Theory',
    venue: 'Main Exam Hall - Block A',
    seatNumber: 'A-42',
    durationMinutes: 180,
    totalMarks: 100,
  },
  {
    id: 'ex-3',
    date: '2026-10-21',
    day: 'Wednesday',
    time: '02:00 PM - 05:00 PM',
    subjectCode: 'CS603',
    subjectName: 'Web Fullstack Engineering',
    examType: 'End-Semester Theory',
    venue: 'Main Exam Hall - Block B',
    seatNumber: 'B-18',
    durationMinutes: 180,
    totalMarks: 100,
  },
  {
    id: 'ex-4',
    date: '2026-10-24',
    day: 'Saturday',
    time: '09:00 AM - 12:00 PM',
    subjectCode: 'CS603L',
    subjectName: 'Web Engineering Practical',
    examType: 'End-Semester Practical',
    venue: 'Software Lab 3',
    seatNumber: 'PC-24',
    durationMinutes: 180,
    totalMarks: 50,
  },
];
