import type { Announcement } from '../types/communication';

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-101',
    title: 'End-Semester Theory & Practical Examination Schedule Released',
    description: 'The tentative timetable for the Fall 2026 End-Semester Examinations for 3rd and 4th year B.Tech students has been published.',
    content: 'All eligible students must check their respective subject codes and venue details under the Exams page. Please note that admit cards will be downloadable 7 days prior to the start of examinations upon clearing any outstanding tuition or library dues.',
    date: '2026-10-01',
    time: '09:30 AM',
    category: 'Exams',
    importance: 'High',
    postedBy: 'Controller of Examinations',
    isRead: false,
    attachmentName: 'End_Sem_Exam_Schedule_Fall2026.pdf',
    attachmentSize: '1.4 MB',
  },
  {
    id: 'ann-102',
    title: 'Campus Recruitment Drive: TechCorp Global Internship Program',
    description: 'TechCorp Global is conducting an on-campus placement drive for 6th & 7th Semester CSE/ECE students for Software Engineering Internships.',
    content: 'Interested candidates with a CGPA >= 7.5 and no active backlogs are required to register through the placement portal before October 8th, 2026. Pre-placement talk will be held in Auditorium Hall C.',
    date: '2026-09-29',
    time: '02:15 PM',
    category: 'Placement',
    importance: 'High',
    postedBy: 'Training & Placement Office',
    isRead: true,
    attachmentName: 'TechCorp_Job_Description_2026.pdf',
    attachmentSize: '850 KB',
  },
  {
    id: 'ann-103',
    title: 'Library Maintenance Notice & Digital Portal Access',
    description: 'The physical central library will remain closed on Sunday for system upgrades. Digital e-books portal will remain operational.',
    content: 'Central library server maintenance will take place this Sunday from 08:00 AM to 06:00 PM. Book returns will be granted a 24-hour grace extension.',
    date: '2026-09-27',
    time: '11:00 AM',
    category: 'General',
    importance: 'Normal',
    postedBy: 'Chief Librarian',
    isRead: true,
  },
  {
    id: 'ann-104',
    title: 'Annual Hackathon "HackCMS 2026" Registrations Open',
    description: 'Join the annual 36-hour hackathon hosted by the Computer Science Department. Grand prize pool of $5,000!',
    content: 'HackCMS 2026 invites teams of 2 to 4 students to build innovative solutions in AI/ML, Cloud Infrastructure, and Sustainable Tech. Register your team today.',
    date: '2026-09-25',
    time: '04:00 PM',
    category: 'Events',
    importance: 'Medium',
    postedBy: 'ACM Student Chapter',
    isRead: true,
    attachmentName: 'HackCMS_Guidelines.pdf',
    attachmentSize: '2.1 MB',
  },
];
