import type { StudentProfile } from '../types/student';

export const mockStudentProfile: StudentProfile = {
  id: 'stu-user-101',
  studentId: 'STU2024-8942',
  firstName: 'Alex',
  lastName: 'Vance',
  fullName: 'Alex Vance',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  email: 'alex.vance@student.cms.edu',
  phone: '+1 (555) 234-8901',
  age: 21,
  dateOfBirth: '2004-06-15',
  gender: 'Male',
  bloodGroup: 'O+',
  address: '452 University Avenue, Suite 3B, College Town, NY 10012',
  academic: {
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    academicYear: '3rd Year',
    semester: 6,
    section: 'Section A',
    rollNo: '24CSE042',
    enrolmentDate: '2022-08-20',
    advisorName: 'Dr. Robert Chen',
    advisorEmail: 'robert.chen@faculty.cms.edu',
  },
  parent: {
    name: 'Eleanor Vance',
    relationship: 'Mother',
    contact: '+1 (555) 987-6543',
    email: 'eleanor.vance@email.com',
    occupation: 'Senior Financial Analyst',
    emergencyContact: '+1 (555) 987-6544',
  },
  accommodation: {
    status: 'Hosteller',
    hostelBlock: 'Block B (Aryabhata Hall)',
    roomNumber: 'B-304',
    wardenName: 'Prof. Marcus Brody',
    wardenContact: '+1 (555) 444-1234',
  },
  transport: {
    isCabUser: true,
    busRouteNumber: 'Route #12 (North Campus Express)',
    pickupPoint: 'North Gate Terminal, Stop 3',
    driverName: 'David Miller',
    driverContact: '+1 (555) 333-8899',
  },
};
